server:
  port: ${PORT_TO_EXPOSE:8080}

spring:
  datasource:
    url: jdbc:postgresql://service-postgres.postgres:5432/employees
    username: employees
    password: employees
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://service-registry.service:8080/eureka

hystrix:
  command:
    AccessExpressionCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

security:
  session:
    duration: 43200
  ignored: /ui/digest,/ui/activate
  user:
    password: password
  oauth:
    client:
      clientId: carspark
      secret: test
      grantTypes: login_password
      scope: carspark
  validation:
    redirectUriRegex: (.*localhost.*)

logging:
  level:
    ROOT: INFO
    ru.vtb: DEBUG
    org.springframework: INFO

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://172.19.19.226:31564/employees
    username: employees
    password: employees
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8080

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    AccessExpressionCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000