server:
  port: ${PORT_TO_EXPOSE:8080}

eureka:
  instance:
    hostname: service-registry
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://service-registry.netflix:8080/eureka

---
spring:
  profiles: dev

server:
  port: 8761