server:
  port: ${PORT_TO_EXPOSE:8080}

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://${discovery-host}:${discovery-port}/eureka/

zuul:
  sensitiveHeaders:
  routes:
    auth:
      serviceId: auth
      sensitiveHeaders:
    dicts:
      path: /dicts/**
      serviceId: dicts
    employees:
      path: /employees/**
      serviceId: employees
    cars:
      path: /cars/**
      serviceId: cars
