server:
  port: ${PORT_TO_EXPOSE:8080}

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://service-registry:8080/eureka

zuul:
  sensitiveHeaders:
  include-debug-header: true
  zuul.debug.request: true
  stripPrefix: false
  routes:
    auth:
      serviceId: auth
      sensitiveHeaders:
    dicts:
      serviceId: dicts
      sensitiveHeaders:
    cars:
      serviceId: cars
      sensitiveHeaders:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eureka:
    enabled: true
    ReadTimeout: 40000
    ConnectTimeout: 40000

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

---
spring:
  profiles: dev

server:
  port: 9098

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/