server:
  port: ${PORT_TO_EXPOSE:8080}

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://${discovery-host}:${discovery-port}/eureka/

zuul:
  sensitiveHeaders:
  routes:
    auth:
      serviceId: auth
      sensitiveHeaders:

---
spring:
  profiles: dev

server:
  port: 9099

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/