server:
  port: ${PORT_TO_EXPOSE:8080}

spring:
  datasource:
    url: jdbc:postgresql://service-postgres.postgres:5432/dicts
    username: dicts
    password: dicts
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://service-registry.service:8080/eureka

feign:
  oauth2.enabled: true

security:
  oauth2:
    client:
     client-id: carspark
     grant-type: login_password
    resource:
      jwt:
        keyValue: -----BEGIN PUBLIC KEY-----
                  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3W9lacXN4YTKYuq6dpi2
                  plf6pjOKoa1UmWUo1GaZniGCMbNklq4bEFEvvOsPt7++/8dMLf2BgIsf+hj9BBxJ
                  BPV8DYKfw5sK83XHP4yM3pZnXp5vxkgXcqyL/JN4A1+qdwjL2UrUZoQHjAEhs4dT
                  Ygj5QFJ9GbfF98A0yrRyfNDUQ/fWY0hXfchf07Cur4oZ6Xe3ocS/SBg6MRiDLu+g
                  Qwbbabl/qVWdpOKRkLRyDWElUyPOZUrw1VnrCPu2excuhQZ/0XU7ijCq3YZnTB1p
                  1hCAp+yaQ1zvf0qJT4UWiNwddO6xZAwwQHWgIKhTpQNcaAGExB+1JE1NJqk2pim7
                  yQIDAQAB
                  -----END PUBLIC KEY-----

kafka:
  bootstrap-servers: kafka01.kafka:9092
  topic:
    reference: reference.t

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://172.19.19.226:31564/dicts
    username: dicts
    password: dicts
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8081

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/

kafka:
  bootstrap-servers: localhost:9092
  topic:
    reference: reference.t