server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://52.6.242.125:5432/carpark
    username: nfo
    password: 123
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
