server:
  port: ${PORT_TO_EXPOSE:8080}


spring:
  datasource:
    url: jdbc:postgresql://service-postgres.postgres:5432/preorders
    username: preorders
    password: preorders
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://${discovery-host}:${discovery-port}/

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://172.19.19.226:31564/preorders
    username: preorders
    password: preorders
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8084

eureka:
  instance.preferIpAddress: true
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/